spring.application.name=AirPowerServer

# HTTPS Configuration
server.ssl.key-store=classpath:airpower_server_keystore.p12
server.ssl.key-store-password=ifpe-airpower
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=airpowerserver
server.port=8443
server.ssl.enabled=true

# JWT Properties
jwt.secret=93!Hn,M3/2w5;0y64>@.LOk
jwt.expirationMs=86400000

spring.datasource.url=jdbc:postgresql://192.168.1.25:5432/thingsboard
spring.datasource.username=postgres
spring.datasource.password=ifpe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Se JWT_TOKEN_SIGNING_KEY não estiver definida no ThingsBoard, use o valor padrão:
thingsboard.jwt.secret.base64=thingsboardDefaultSigningKey