spring.application.name=AirPowerServer

# HTTPS Configuration
server.ssl.key-store=classpath:airpower_server_keystore.p12
server.ssl.key-store-password=ifpe-airpower
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=airpowerserver
server.port=8443
server.ssl.enabled=true

# JWT Properties
airpower.jwt.secret=93!Hn,M3/2w5;0y64>@.LOk
airpower.jwt.expirationMinutes=10
airpower.refreshToken.expirationDays=25

# --- CONFIGURAÇÃO DO BANCO DE DADOS 'airpower' ---
spring.datasource.airpower.jdbc-url=jdbc:postgresql://192.168.56.101:5432/airpower
spring.datasource.airpower.username=airpowerserver
spring.datasource.airpower.password=ifpe

# --- CONFIGURAÇÃO DO BANCO DE DADOS 'ThingsBoard'---
spring.datasource.thingsboard.jdbc-url=jdbc:postgresql://192.168.56.101:5432/thingsboard
spring.datasource.thingsboard.username=airpowerserver
spring.datasource.thingsboard.password=ifpe

thingsboard.jwt.secret.base64=thingsboardDefaultSigningKey

# URL da API do ThingsBoard
thingsboard.api.url=https://localhost:8080

# AES CONFIG
aes.config.key="#)p8A)43JmWhqP"